# Import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import TfidfTransformer


# Import Datasets

In [2]:
train_df = pd.read_excel("Data_Train.xlsx")
test_df = pd.read_excel("Data_Test.xlsx")


# Text Pre-processing

In [3]:
corpus = []

for i in range(0, len(train_df)):
    review = re.sub('[^a-zA-Z]', ' ', train_df["STORY"][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
print(len(corpus))

7628


# Create Bag-of-Words model

In [4]:
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = train_df["SECTION"].values

# Train - Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 0)

# Model Evaluation

In [6]:
def model_evaluation(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    ac = accuracy_score(y_test, y_pred)
    print("Confusion Matrix")
    print(cm)
    print("Accuracy: ", ac)

# Model fitting and testing

In [7]:
NBClassifier = MultinomialNB()
NBClassifier.fit(X_train, y_train)
nb_y_pred = NBClassifier.predict(X_test)
model_evaluation(y_test, nb_y_pred)


Confusion Matrix
[[260   3   0   2]
 [  6 396   4   4]
 [  5   4 258   0]
 [  1   2   0 200]]
Accuracy:  0.9729257641921397


# Run the model on test data and predict the categories

In [8]:
X1 = cv.transform(test_df['STORY'])
test_predict = NBClassifier.predict(X1)
print(test_predict)

[1 2 1 ... 1 0 1]


In [9]:
test_df["SECTION"] = test_predict

# Export the data to a .csv file

In [10]:
test_df.to_csv('submission.csv', index=False)

# DONE!